/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Leagues: typeof import('./src/components/Leagues.vue')['default']
    Matches: typeof import('./src/components/Matches.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMatches: typeof import('./src/components/TeamMatches.vue')['default']
    Teams: typeof import('./src/components/Teams.vue')['default']
    TeamStats: typeof import('./src/components/TeamStats.vue')['default']
  }
}
